name = "SkyBlock Enhanced"
version = "5.0.0-beta.6"
description = "The only Hypixel SkyBlock modpack you need. Built for modern Minecraft — 60+ optimized mods, a guided setup wizard, and a config system no other pack comes close to match."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b53aa97eaf2e3bb1af9436d74998df168a99e1a499d2fcc3c35415eb974f5ff"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
