name = "SkyBlock Enhanced"
version = "5.0.0-beta.6"
description = "The only Hypixel SkyBlock modpack you need. Built for modern Minecraft — 60+ optimized mods, a guided setup wizard, and a config system no other pack comes close to match."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ceb940efa9155eb7dae389962f66fc07ad2f85b45f2c5f48fad717d563799cd8"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
