name = "SkyBlock Enhanced"
version = "5.0.0-beta.5"
description = "The only Hypixel SkyBlock modpack you need. Built for modern Minecraft — 60+ optimized mods, a guided setup wizard, and a config system no other pack comes close to match."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67e5927e5bed1bf4399dd71cdb37f590100ba9f0430d8e41b0ca780438a363bd"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
