name = "SkyBlock Enhanced"
version = "4.0.8"
description = "The only Hypixel SkyBlock modpack you need. Built for modern Minecraft — 60+ optimized mods, a guided setup wizard, and a config system no other pack comes close to match."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "417a5047c68bfba4565bae65e203e958634f7007d5d8358b0a1095ce632382d0"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
