name = "SkyBlock Enhanced"
version = "4.0.8"
description = "The only Hypixel SkyBlock modpack you need. Built for modern Minecraft — 60+ optimized mods, a guided setup wizard, and a config system no other pack comes close to match."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "905d72a0b8e43946a8058440186bb08b0629068ab9535f6f55fe6ef9d5826a4e"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
