name = "SkyBlock Enhanced Modern Edition"
version = "2.5.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3b7b997b3643a81f8c0bff87315990737f93635c461def80e3e3875c46a36b4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
