name = "SkyBlock Enhanced Modern Edition"
version = "2.5.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f35c4177f6b5c2ba1da40a0e824886384e3d751186aff7244d499b143ea1311c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
