name = "SkyBlock Enhanced Modern Edition"
version = "2.3.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "432ba28832de133fb3ffff064e081bd9a20c8892a7ab938d57030a099a2e93b6"

[versions]
fabric = "0.18.3"
minecraft = "1.21.5"
