name = "SkyBlock Enhanced Modern Edition"
version = "2.3.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bda4fcc4f3a1a843c0c71fcd66ccabb7f38ee2c8f5163f0d4b0961faf4b783cd"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"
