name = "SkyBlock Enhanced Modern Edition"
version = "2.3.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5684f9eb6d6f016cc2df20680d8e662752f545eaaa94f7acf07201f429100418"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"
