name = "SkyBlock Enhanced Modern Edition"
version = "2.3.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e297a1be3fcdde3a8257665b6d600dffde0844e53bc2a5eb4109850d97a638ed"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"
